### ISSUE TITLE
Emy issue: Closest track reference does not contain searched subUid

### ISSUE THREAD

**Issue by fpavlic** [AddictedCS/soundfingerprinting#174] opened 2021-11-05 17:47 UTC
Hi,
I'm getting following issue using Emy. Any idea where to start/check for this issue?

`ERROR SoundFingerprinting.Storage.DAO.TrackRefSubFingerprintsStorage 359 Closest track reference does not contain searched subUid 3087166. Found starting @3110049 with 1010 counts. `

Additional info. Instance that failed, after restart cannot start.
Following error:
`Trying to insert a track with a lower start fingerprint ID 3082780 than prev track in the BTree 3085078`

**Comment by AddictedCS** [comment] 2023-08-30 13:53
Could not reproduce. Closing it as it is probably not relevant in v8.25.0 (latest version).

**Closed by AddictedCS** 2023-08-30 13:53 UTC
